version: "3.4"
services:
  mongo:
    container_name: mongo-container
    image: mongo:latest
    restart: always
    volumes:
      - ./.data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    build: .
    image: clean-node-api # esse image, nesse caso que já temos o build, é só pra gerar o nome do container
    restart: always
    command:
      - "npm"
      - "start"
    volumes:
      - ./dist:/usr/src/clean-node-api/dist
    ports:
      - "5050:5050"
    links:
      - mongo