version: "3.4"
services:
  mongo:
    container_name: mongo-container
    image: mongo:latest
    restart: always
    volumes:
      - ./.data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    image: node:16
    working_dir: /usr/src/clean-node-api
    restart: always
    command: bash -c "npm i --silent --only=prod && npm run debug"
    volumes:
      - ./dist/:/usr/src/clean-node-api/dist/
      - ./package.json:/usr/src/clean-node-api/package.json
      - ./src/:/usr/src/clean-node-api/src/
    ports:
      - "5050:5050"
      - "9222:9222" # Porta para o socket do debugger
    links:
      - mongo